string action  # The action to trigger.
---
uint8 SUCCESS = 0
uint8 FAILURE = 1
uint8 UNSUPPORTED = 2

uint8 result   # Indicates if the action was successfully triggered.
string message # Informational message about the outcome of the request.